function analyze_batch()


    Dlx_RITE = [...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 1/day 0/T8.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 1/day 3/T8.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 1/day 7/T8.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 2/day 0/T9.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 2/day 3/T9_rigid.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 2/day 7/T9.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 3/day 0/10.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 3/day 3/T10.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 3/day 7/T10.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 4/day 0/T11.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 4/day 3/T11.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 4/day 7/T11.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 5/day 0/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 5/day 3/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 5/day 7/T.sig";...
            ];

         
    Dlx_Sham = [...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 1/day 0/T4_rigid.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 1/day 3/T4.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 1/day 7/T4.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 2/day 0/T5.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 2/day 3/T5.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 2/day 7/T5.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 3/day 0/T6_rigid.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 3/day 3/T6.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 3/day 7/T6.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 4/day 0/T7_rigid.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 4/day 3/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 4/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 5/day 0/T_rigid.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 5/day 3/T_rigid.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 5/day 7/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 6/day 0/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 6/day 3/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 6/day 7/T.sig";...
             ];
    
    Dlx_Ion_CC = [...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 1/day 0/T1.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 1/day 3/T1.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 1/day 7/T1.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 2/day 0/T2.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 2/day 3/T2.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 2/day 7/T2.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 3/day 0/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 3/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 3/day 7/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 4/day 0/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 4/day 3/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 4/day 7/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 5/day 0/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 5/day 3/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 5/day 7/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 6/day 0/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 6/day 3/T.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/IoN-CCI/Mouse 6/day 7/T.sig";...
             ];
         
    % analyze a list of files to be analyzed
    CaMKII_RITE = [... 
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 14/day14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 21/day21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 4/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 4/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 4/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 4/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 4/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 4/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 5/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 5/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 5/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 5/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 5/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 5/day 28/T28.sig";...
             
             ];
    
         
    CaMKII_Ion_CC = ...
            [
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 1/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 1/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 1/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 1/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 1/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 1/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 2/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 2/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 2/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 2/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 2/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 2/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 3/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 3/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 3/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 3/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 3/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 3/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 4/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 4/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 4/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 4/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 4/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 4/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 5/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 5/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 5/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 5/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 5/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 5/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 6/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 6/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 6/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 6/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 6/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 6/day 28/T28.sig";...
            ];
        
    CaMKII_all_SHAM = [...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 1/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 1/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 1/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 1/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 1/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 1/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 2/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 2/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 2/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 2/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 2/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 2/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 3/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 3/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 3/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 3/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 3/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(Com-TN)/Mouse 3/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 4/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 4/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 4/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 4/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 4/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 4/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 5/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 5/day 3/T3_rigid.tif";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 5/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 5/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 5/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 5/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 6/day 0/T0.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 6/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 6/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 6/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 6/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Sham(IoN-CCI)/Mouse 6/day 28/T28.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Mouse 7/day 0/T0";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Mouse 7/day 3/T3.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Mouse 7/day 7/T7.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Mouse 7/day 14/T14.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Mouse 7/day 21/T21.sig";...
             "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Mouse 7/day 28/T28.sig"...
            ];
        
    Day0_extra = ["/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/SHAM/Mouse 7/day 0/T0.sig";...
                  "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/IoN-CCI/Mouse 6/day 0/T0.sig"];
        
    DREADD_control = ...
        ["/Users/lukasfischer/Work/exps/Shiqian/DREADD/Control/Before CNO/Mouse 1/1.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Control/Before CNO/Mouse 2/3.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Control/Before CNO/Mouse 3/5.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Control/After CNO/Mouse 1/2.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Control/After CNO/Mouse 2/4.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Control/After CNO/Mouse 3/6.sig";...
        ];
    
    DREADD_Gi = ...
        ["/Users/lukasfischer/Work/exps/Shiqian/DREADD/Gi/Before/Mouse 1/7.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Gi/Before/Mouse 2/9.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Gi/Before/Mouse 3/11.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Gi/After/Mouse 1/8.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Gi/After/Mouse 2/10.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/DREADD/Gi/After/Mouse 3/12.sig";...
        ];
    
    Keterolac = [ ...
         "/Users/lukasfischer/Work/exps/Shiqian/Keterolac/Mouse 1/Before/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Keterolac/Mouse 1/After/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Keterolac/Mouse 2/Before/Tbaseline.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Keterolac/Mouse 2/After/T60min.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Keterolac/Mouse 3/Before/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Keterolac/Mouse 3/After/T_rigid.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Keterolac/Mouse 4/Before/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Keterolac/Mouse 4/After/T.sig";...
        ];
    
    
    
    carb = [...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 1/Carb 30 mg/Carb before/T_rigid.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 1/Carb 30 mg/Carb 30 min/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 1/Carb 60 mg/Carb 30 min/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 2/Carb baseline/Tcarba baseline.sig";...
          "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 2/Carb 30 mg/T60min_rigid.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 2/Carb 60 mg/T60min.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 3/Carb baseline/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 3/Carb 30 mg/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 3/Carb 60 mg/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 4/Carb baseline/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 4/Carb 30 mg/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Carbamazepine/Mouse 4/Carb 60 mg/T_rigid.sig";...
        ];
    
    pre_decomp = [...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/day 0/T0.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/day 7/T7.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/day 14/T14_rigid.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/Decompression/day 0/T0.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/Before decompression/T.sig";...
 
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/day 0/T.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/day 1/T.sig";... 
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/day 3/T.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/day 5/T.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/day 7/T_rigid.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/day 14/T.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/Decompression/day 0/T0.sig";...
            "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/Before decompression/T.sig";...
           ];
    post_decomp = [...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Decompression/day 1 decompression/T14.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Decompression/day 3 decompression/T3.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Decompression/day 5 decompression/T5.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Decompression/day 7 decompression/T7.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/Decompression/day 1 post decompression/T1.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/Decompression/day 3 post decompression/T3.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/Decompression/day 5 post decompression/T5.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/Decompression/day 7 post decompression/T7.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/day 1 post decompression/T1.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/day 3 post decompression/T3.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/day 5 post decompression/T5.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/day 7 post decompression/T7.sig";...
            
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Decompression/day 1 decompression/T1.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Decompression/day 3 decompression/T3.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Decompression/day 5 decompression/T5.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Decompression/day 7 decompression/T7.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/Decompression/day 1 decompression/T_rigid.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/Decompression/day 3 decompression/T.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/Decompression/day 5 decompression/T.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/Decompression/day 7 decompression/T.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/day 1 post decompression/T1.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/day 3 post decompression/T3.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/day 5 post decompression/T5.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/day 7 post decompression/T7.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/day 1 post decompression/T1.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/day 3 post decompression/T3.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/day 5 post decompression/T5.sig";...
%          "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 4/day 7 post decompression/T7.sig";...
        ];
    
     recomp = [...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Recompression/day 3/T3_rigid.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 1/Recompression/day 7/T7_rigid.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/Recompression/day 3 post recompression/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 2/Recompression/day 7 post recompression/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/Recompression/day 3/T.sig";...
         "/Users/lukasfischer/Work/exps/Shiqian/Decompression/Mouse 3/Recompression/day 7/T.sig";...
     ];
      
    pilocarpine = [...
                   "/Users/lukasfischer/Work/exps/Shiqian/Pilocarpine/T2-4/T2-004-1-450.sig";...
                   "/Users/lukasfischer/Work/exps/Shiqian/Pilocarpine/Trial 1/After Pilocarpine/T1.sig";...
                   "/Users/lukasfischer/Work/exps/Shiqian/Pilocarpine/Trial 1/Before Pilocarpine/T1.sig";...
                   "/Users/lukasfischer/Work/exps/Shiqian/Pilocarpine/Trial 2/After Pilocarpine/T2.sig";...
                   "/Users/lukasfischer/Work/exps/Shiqian/Pilocarpine/Trial 2/Before Pilocarpine/T2.sig";...
                   "/Users/lukasfischer/Work/exps/Shiqian/Pilocarpine/Trial 3/After Pilocarpine/T3.sig";...
                   "/Users/lukasfischer/Work/exps/Shiqian/Pilocarpine/Trial 3/Before Pilocarpine/T3_rigid.sig";...
                  ];
    
    Gq_C21_FLIT = [...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 1/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 1/day 7/T7.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 1/day 14/T14.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 1/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 1/day 28/T28.sig";...
%         
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 2/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 2/day 7/T7.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 2/day 14/T14.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 2/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 2/day 28/T28.sig";...
%         
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 3/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 3/day 7/T7.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 3/day 14/T14.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 3/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 3/day 28/T28.sig";...
        
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 4/day 0/T0.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 4/day 7/T7.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 4/day 14/T14_rigid.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 4/day 21/T21.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+FLIT/mouse 4/day 28/T28.sig";...
        ];
    
    Gq_C21_SHAM = [...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 1/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 1/day 7/T7.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 1/day 14/T14.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 1/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 1/day 28/T28.sig";...
%         
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 2/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 2/day 7/T7.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 2/day 14/T14.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 2/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 2/day 28/T28.sig";...
%         
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 3/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 3/day 7/T7.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 3/day 14/T14_rigid.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 3/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 3/day 28/T28.sig";...
        
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 4/day 0/T0.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 4/day 7/T7.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 4/day 14/T14.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 4/day 21/T21.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/Gq+C21+sham/mouse 4/day 28/T28.sig";...
        ];
    Vector_C21_FLIT = [...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 1/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 1/day 7/T7_rigid.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 1/day 14/T14_rigid.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 1/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 1/day 28/T28_rigid.sig";...
%         
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 2/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 2/day 7/T7_rigid.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 2/day 14/T14_rigid.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 2/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 2/day 28/T28.sig";...
%         
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 3/day 0/T0.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 3/day 7/T7.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 3/day 14/T14.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 3/day 21/T21.sig";...
%         "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 3/day 28/T28.sig";...
        
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 4/day 0/T0_rigid.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 4/day 7/T7.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 4/day 14/T14.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 4/day 21/T21.sig";...
        "/Users/lukasfischer/Work/exps/Shiqian/Gq imaging data_01282021/vector+C21+FLIT/mouse 4/day 28/T28.sig";...
        ];
              
    flist = {CaMKII_Ion_CC, CaMKII_all_SHAM};
    flist = {Day0_extra}; 
    flist = {Dlx_RITE, Dlx_Ion_CC, Dlx_Sham}; % , 
    flist = {CaMKII_Ion_CC}; 
    flist = {pre_decomp, post_decomp};
    flist = {CaMKII_RITE, CaMKII_Ion_CC, CaMKII_all_SHAM}; 
    
    flist = {CaMKII_RITE, CaMKII_Ion_CC, CaMKII_all_SHAM};
    flist = {DREADD_control, DREADD_Gi};
    flist = {Keterolac, carb, recomp};
    flist = {Dlx_RITE, Dlx_Ion_CC, Dlx_Sham}; %
    flist = {pilocarpine};
    flist = {Keterolac, carb, recomp};
    flist = {Gq_C21_FLIT, Gq_C21_SHAM, Vector_C21_FLIT};
    

    
    analyze_SIG = true;
    analyze_CORR = true;
    analyze_AUC = true;
    
    % parameter defining by which amount we weigh the neuropil to be subtracted from the roi signal
    neuropil_weight = 0.8;

    % percentile of datapoints used to calculate baseline for df/f 
    baseline_percentile = 50;   

    % lowpass filter cutoff (you have to re-loead the .sig file for this to take effect)
    lowpass_filter_cutoff = 0.3;

    % data acquisition rate. This might be something we want to be able to change later
    fs = 5.5; % Hz
    
    % parameters for transient detection
    std_threshold = 6;
    transient_baseline_percentile = 20;
    gap_tolerance_frames = 3;
    min_transient_length = 3;
    event_threshold = 0.5;
    transient_num_threshold = 5;
    
    for f_i=1:length(flist)
        if analyze_SIG == true % analyze .sig files

            for i=1:size(flist{f_i},1)
                disp('Analyzing SIG: ' + flist{f_i}(i)),
                [fPath,fName,fType] = fileparts(flist{f_i}(i));
                full_path = strcat(fName,fPath);
                fPath = strcat(fPath, filesep);


                % load raw fluorescence and metadata
                sigfile = strcat(fPath, fName, '.sig');
                extrafile = strcat(fPath, fName, '.extra');
        %         roimaskfile = strcat(fPath, fName, '.rois');
                roiFluorescences_all = load(sigfile);
                metadata = load(extrafile, '-mat');

                % crop neuropil columns
                roiFluorescences = roiFluorescences_all(:,1:(size(roiFluorescences_all,2)/2)); 
                roiFluorescences_PIL = roiFluorescences_all(:,(size(roiFluorescences_all,2)/2)+1:end); 

                % eliminate NaN values at the start and the end
                crop_start = 0;
                crop_end = 0;
                j = 1;
                while any(isnan(roiFluorescences(j,:)))
                    j = j + 1;
                    crop_start = crop_start + 1;
                end
                j = 0;
                while any(isnan(roiFluorescences(end-j,:)))
                    j = j + 1;
                    crop_end = crop_end + 1;
                end
                roiFluorescences = roiFluorescences(crop_start+1:end-crop_end,:);
                roiFluorescences_PIL = roiFluorescences_PIL(crop_start+1:end-crop_end,:);
                metadata.meanBrightness = metadata.meanBrightness(:,crop_start+1:end-crop_end);

                % analyze DFF data and store
                baseline_fit = robustfit(linspace(1,size(roiFluorescences,1),size(roiFluorescences,1)),metadata.meanBrightness');
                dff_background = baseline_fit(1) + linspace(1,size(roiFluorescences,1),size(roiFluorescences,1)) * baseline_fit(2);
                dff = calculateDFF2((roiFluorescences-(neuropil_weight*roiFluorescences_PIL))+dff_background', baseline_percentile);

                %dff = calculateDFF(roiFluorescences);
                stopFrame = size(dff,1);
                stopEdit.String = num2str(stopFrame);
                startEdit.String = '1';

                % prep matrizes for deconvolution
                foopsi_filtered = zeros(size(dff));
                foopsi_events = zeros(size(dff));
                foopsi_options = {};
                % low pass filter signal
                dff_filtered = zeros(size(dff));
                for j=1:size(dff,2)
                    % linearly inteprolate any NaN datapoints
                    isnan_idx = find(isnan(dff(:,j)));
                    real_idx = find(~isnan(dff(:,j)));
                    dff_filtered(real_idx,j) = dff(real_idx,j);
                    dff_filtered(isnan_idx,j) = interp1(real_idx,dff_filtered(real_idx,j),isnan_idx);
                    dff(isnan_idx,j) = interp1(real_idx,dff(real_idx,j),isnan_idx);
                    dff_filtered(:,j) = lowpass(dff_filtered(:,j),lowpass_filter_cutoff,fs);
                    
                    baseline_dff = dff_filtered(:,i);
                    x_vals = linspace(1,length(baseline_dff),length(baseline_dff));
                    baseline_fit = robustfit(x_vals, baseline_dff);
                    baseline_correction = baseline_fit(1) + baseline_fit(2)*x_vals;
                    dff(:,i) = dff(:,i) - baseline_correction';
                    dff_filtered(:,i) = dff_filtered(:,i) - baseline_correction';

                    [c, s, options] = deconvolveCa(dff(:,j), 'foopsi', 'ar1', 'smin', -3, 'optimize_pars', true, 'optimize_b', true); % ar2, smin -1
                    foopsi_filtered(:,j) = c;
                    foopsi_events(:,j) = s;
                    foopsi_options{end+1} = options;
                end


                dff_temp = dff;
                dff_filtered_temp = dff_filtered;
                roiFluorescences_temp = roiFluorescences;
                metadata_temp = metadata;
                foopsi_filtered = foopsi_filtered;
                foopsi_events = foopsi_events;
                foopsi_options = foopsi_options;
                save(strcat(fPath,filesep,fName,'_analyzed.mat'), 'dff_temp', 'roiFluorescences_temp', 'full_path', 'dff_filtered_temp', 'metadata_temp', 'foopsi_filtered', 'foopsi_events', 'foopsi_options');
            end
        end

        if analyze_CORR == true
            for i=1:size(flist{f_i},1)
                disp('Analyzing CORR: ' + flist{f_i}(i)),
                [fPath,fName,fType] = fileparts(flist{f_i}(i));
                full_path = strcat(fPath,filesep,fName,'_analyzed.mat');
                % load analyzed data
                loaded_data = load(full_path, '-mat');
                dff = loaded_data.dff_temp;
                dff_filtered = loaded_data.dff_filtered_temp;
                roiFluorescences = loaded_data.roiFluorescences_temp;
                metadata = loaded_data.metadata_temp;
                foopsi_filtered = loaded_data.foopsi_filtered;
                foopsi_events = loaded_data.foopsi_events;
                foopsi_options = loaded_data.foopsi_options;
        %             roi_transients = loaded_data.roi_transients_temp;
                stopFrame = size(dff,1);
                stopEdit.String = num2str(stopFrame);
                startEdit.String = '1';    

                % right now all rois are included in the batch process
                inc_rois = linspace(1,size(dff,2),size(dff,2));
                roi_dff = dff_filtered(:,inc_rois);
                roi_foopsi = foopsi_events(:,inc_rois);
                roi_foopsi_filtered = foopsi_filtered(:,inc_rois);

                pairwise_corr = zeros(size(roi_dff,2),size(roi_dff,2));
                geom_mean = zeros(size(roi_dff,2),size(roi_dff,2));


                for i=1:size(roi_dff,2) % calculate pairwise correlation for each neuron
                    for j=1:size(roi_dff,2)
                        if i ~= j
%                             pairwise_corr(i,j) = corr(roi_dff(:,i),roi_dff(:,j),'Type','Spearman');
%                             pairwise_corr(i,j) = corr(roi_foopsi_filtered(:,i),roi_foopsi_filtered(:,j),'Type','Spearman');
                            pairwise_corr(i,j) = corr(dff_filtered(:,i),dff_filtered(:,j),'Type','Spearman');
                            mean_event_i = length(find(roi_foopsi(:,i)))/size(roi_foopsi,1)*fs;
                            mean_event_j = length(find(roi_foopsi(:,j)))/size(roi_foopsi,1)*fs;
                            geom_mean(i,j) = geo_mean( [mean_event_i, mean_event_j] );
                        else
                            pairwise_corr(i,j) = NaN;
                        end
                    end
                end
    %             disp([size(pairwise_corr),size(geom_mean)])
                save(strcat(fPath, filesep, fName, '_CORR.mat'), 'pairwise_corr', 'geom_mean');

            end
        end

        if analyze_AUC == true


            for i=1:size(flist{f_i},1)
                disp('Analyzing AUC: ' + flist{f_i}(i)),
                [fPath,fName,fType] = fileparts(flist{f_i}(i));
                full_path = strcat(fPath,filesep,fName,'_analyzed.mat');
                % load analyzed data
                loaded_data = load(full_path, '-mat');
                dff = loaded_data.dff_temp;
                dff_filtered = loaded_data.dff_filtered_temp;
                roiFluorescences = loaded_data.roiFluorescences_temp;
                metadata = loaded_data.metadata_temp;
                foopsi_filtered = loaded_data.foopsi_filtered;
                foopsi_events = loaded_data.foopsi_events;
                foopsi_options = loaded_data.foopsi_options;
        %             roi_transients = loaded_data.roi_transients_temp;
                startFrame = 1;
                stopFrame = size(dff,1);
                stopEdit.String = num2str(stopFrame);
                startEdit.String = '1';    


                % right now all rois are included in the batch process
                inc_rois = linspace(1,size(dff,2),size(dff,2));
                roi_dff = dff(:,inc_rois);
                roi_foopsi = foopsi_events(:,inc_rois);

%                 roi_transients = id_transients(dff_filtered(:,inc_rois),std_threshold,transient_baseline_percentile, gap_tolerance_frames, min_transient_length);
                roi_transients = id_transients_foopsi(dff_filtered(:,inc_rois),foopsi_events,foopsi_filtered);

                for i=1:size(roi_transients,2)
                    baseline_dff = dff_filtered(:,i);
        %             for j=1:size(GUIHandles.roi_transients{i},1)
        %                 baseline_dff(GUIHandles.roi_transients{i}(j,1):GUIHandles.roi_transients{i}(j,2)) = NaN;
        %             end
                    x_vals = linspace(1,length(baseline_dff),length(baseline_dff));
                    baseline_fit = robustfit(x_vals, baseline_dff);
                    baseline_correction = baseline_fit(1) + baseline_fit(2)*x_vals;
                    dff(:,i) = dff(:,i) - baseline_correction';
                    dff_filtered(:,i) = dff_filtered(:,i) - baseline_correction';
                end
                
                AUC_fulltrace = [];
                AUC_ind = [];
                AUC_global = [];
                AUC_all = [];

                tot_AUC_ind = [];
                tot_AUC_global = [];

                for j=1:size(roi_dff,2) % calculate AUC for each neuron
                    if size(roi_transients{j},1) > 0
                        [roi_transients_individual, roi_transients_global, fraction_active_time] = transient_event(roi_dff,roi_transients(inc_rois),event_threshold,startFrame,stopFrame,j);
                        if size(roi_transients_individual) > 0
                            transient_AUC_individual = calc_transient_AUC(roi_dff(:,j), roi_transients_individual, startFrame, stopFrame, fs);
                        else
                            transient_AUC_individual = [];
                        end

                        if size(roi_transients_global) > 0
                            transient_AUC_global = calc_transient_AUC(roi_dff(:,j), roi_transients_global, startFrame, stopFrame, fs);
            %                 transient_AUC_global = transient_AUC_global / max(transient_AUC_global);
                        else
                            transient_AUC_global = [];
                        end 

                        auc_max = max(vertcat(transient_AUC_individual,transient_AUC_global));

                        tot_AUC_ind = vertcat(tot_AUC_ind, sum(transient_AUC_individual));
                        tot_AUC_global = vertcat(tot_AUC_global, sum(transient_AUC_global));
                        
%                         if tot_AUC_ind<0 | tot_AUC_global<0
%                             disp('AA');
%                         end

                        transient_AUC_individual = transient_AUC_individual / auc_max; % normalize transients of one cell
                        transient_AUC_global = transient_AUC_global / auc_max;
                        AUC_ind = vertcat(AUC_ind,transient_AUC_individual(~isnan(transient_AUC_individual)));
                        AUC_global = vertcat(AUC_global,transient_AUC_global(~isnan(transient_AUC_global)));

            %             AUC_all = vertcat(AUC_all,transient_AUC_individual(~isnan(transient_AUC_individual)));
            %             AUC_all = vertcat(AUC_all,transient_AUC_global(~isnan(transient_AUC_global)));
                    else
                        tot_AUC_ind = vertcat(tot_AUC_ind, 0);
                        tot_AUC_global = vertcat(tot_AUC_global, 0);
                    end    
                end

                % specify variables that will keep track of results
                tot_num_transients = zeros(size(roi_dff,2),1);      % number of transients 
                num_global_transients = zeros(size(roi_dff,2),1);   % number of transients that are part of global events
                fraction_global_transients = zeros(size(roi_dff,2),1);   % number of transients that are part of global events

                [fraction_active, event_idx] = calc_fraction_active(dff(:, inc_rois), roi_transients, event_threshold);

                for j=1:size(roi_dff,2) % run through every neuron and count how many transients it has and how many of those are part of a global event
                    transient_idx = roi_transients{j};
                    if size(transient_idx,1) > 0
                        onset_idx = transient_idx(:,1);
                        offset_idx = transient_idx(:,2);  
                    else
                        onset_idx = [];
                        offset_idx = [];
                    end

                    if size(onset_idx) > 0
                        for k=1:size(onset_idx,1)
                            if onset_idx(k) > startFrame && offset_idx(k) < stopFrame
                                if size(intersect(onset_idx(k):offset_idx(k),find(event_idx)),1) > 1
                                    num_global_transients(j) = num_global_transients(j) + 1;
                                end
                                tot_num_transients(j) = tot_num_transients(j) + 1;
                            end
                        end
                    end    
                end

                for j=1:size(roi_dff,2) % calculate the fraction of transients that are part of global events
                    if tot_num_transients(j) > transient_num_threshold
                        fraction_global_transients(j) = num_global_transients(j)/tot_num_transients(j);
                    else
                        fraction_global_transients(j) = NaN;
                    end
                end

                x_vals = linspace(0,size(roi_dff,1),size(roi_dff,1))/fs;
                for j=1:size(roi_dff,2)
                    y_vals = dff(:,j);
                    t_auc = trapz(x_vals, y_vals);
                    if ~isnan(t_auc)
                        AUC_fulltrace = [AUC_fulltrace, t_auc];
                    end
                    
                end
                
                 % calculate AUC for each neuron to save in results file and plot in scatterplot
                AUC_ind = {};
                AUC_global = {};
                AUC_ind_scatter = [];
                AUC_global_scatter = [];
                AUC_ind_fraction_active = [];
                AUC_global_fraction_active = [];
                for j=1:size(roi_dff,2)
                    if size(roi_transients{j},1) > 0
                        [roi_transients_individual, roi_transients_global, fraction_active_time] = transient_event(roi_dff,roi_transients,event_threshold,startFrame,stopFrame,j);
                        if size(roi_transients_individual) > 0
                            transient_AUC_individual = calc_transient_AUC(roi_dff(:,j), roi_transients_individual, startFrame, stopFrame, fs);
                            AUC_ind{end+1} = transient_AUC_individual(~isnan(transient_AUC_individual));
                            AUC_ind_scatter = vertcat(AUC_ind_scatter,transient_AUC_individual(~isnan(transient_AUC_individual)));
                        else
                            AUC_ind{end+1} = {};
                        end
                        if size(roi_transients_global) > 0
                            transient_AUC_global = calc_transient_AUC(roi_dff(:, j), roi_transients_global, startFrame, stopFrame, fs);
                            AUC_global{end+1} = transient_AUC_global(~isnan(transient_AUC_global));
                            AUC_global_scatter = vertcat(AUC_global_scatter,transient_AUC_global(~isnan(transient_AUC_global)));
                        else
                            AUC_global{end+1} = {};
                        end     
                    end

                end

                tot_num_transients = tot_num_transients;
                num_global_transients = num_global_transients;
                fraction_global_transients = fraction_global_transients;
                transient_data = horzcat(tot_num_transients-num_global_transients,num_global_transients);


                % create results table
                results_table = table(linspace(1,size(roi_dff,2),size(roi_dff,2))',...
                                      tot_num_transients,...
                                      num_global_transients,...
                                      fraction_global_transients,...
                                      'VariableNames', {'roi number','total number of transients', 'global event transients', 'fraction transients global'});

                % write to excel file
                writetable(results_table, strcat(fPath, filesep, fName, '_results.xlsx'));

                save(strcat(fPath, filesep, fName, '_AUC.mat'), 'AUC_ind', 'AUC_global','tot_AUC_ind','tot_AUC_global','tot_num_transients','num_global_transients','fraction_global_transients', 'AUC_fulltrace', 'fraction_active_time');

            end
        end
    end
end

function roi_transients = id_transients(dff,std_threshold,baseline_percentile, gap_tolerance_frames, min_transient_length)
    roi_transients = {};

    for i=1:size(dff,2)
        % calculate percentile threshold only from values around the mean
        full_roi_std = nanstd(dff(:,i));
        dff_for_prctile = dff(dff(:,i)>(-2*full_roi_std) & dff(:,i)<(2*full_roi_std),i);
        prctile_threshold = prctile(dff_for_prctile,baseline_percentile);

        roi_std = nanstd(dff(dff(:,i) < prctile_threshold,i));
        roi_mean = nanmean(dff(dff(:,i) < prctile_threshold,i));
        transient_high = find(dff(:,i) > (std_threshold*roi_std)+roi_mean);

%         roi_std = nanstd(dff(dff(:,i) < prctile(dff(:,i),baseline_percentile),i));
%         roi_mean = nanmean(dff(dff(:,i) < prctile(dff(:,i),baseline_percentile),i));
%         transient_high = find(dff(:,i) > (std_threshold*roi_std)+roi_mean);

        idx_diff = diff(transient_high);
        if size(transient_high,1) > 0
            idx_diff = vertcat(transient_high(1),idx_diff);

    %         onset_idx = transient_high(idx_diff>gap_tolerance_frames)-1;
    %         offset_idx = transient_high(find(idx_diff>gap_tolerance_frames)-1)+1;
    %         offset_idx = circshift(offset_idx,-1);

            % below is an ugly way to identify transients
            j = 1;
            onset_idx = [];
            offset_idx = [];
            dff_max = [];
            while j <= size(dff(:,i),1)
                transient_start = j;
                end_transient = false;
                transient_OK = false;

                if dff(j,i) > (std_threshold*roi_std)+roi_mean
                    while ~end_transient && (j<size(dff,1))
                        if (dff(j,i) <= (std_threshold*roi_std)+roi_mean) || (j >= size(dff,1))
                            end_transient = true;
                        end
                        j = j+1;
                    end
                    transient_end = j;

                    % check if transient is at lesat min_transient_length long
                    if (transient_end - transient_start) > min_transient_length
                        transient_OK = true;
                    end

                    % check if the last transient is at least gap_tolerance away, if no: combine transients
                    if size(offset_idx) > 0
                        if transient_OK && (transient_start - offset_idx(end) < gap_tolerance_frames)
                            offset_idx(end) = transient_end;
                            transient_OK = false;
                        end
                    end

                    if transient_OK
                        onset_idx = vertcat(onset_idx,transient_start);
                        offset_idx = vertcat(offset_idx, transient_end);
                        dff_max = vertcat(dff_max, max(dff(onset_idx:offset_idx,i)));
                    end
                end
                j = j+1;
            end

            % calculate the length of each transient and reject those too short to be considered
    %         index_adjust = 0;
    %         for j=1:size(onset_idx,1)
    %             temp_length = offset_idx(j-index_adjust) - onset_idx(j-index_adjust);
    %             if temp_length < min_transient_length
    %                 onset_idx(j-index_adjust) = [];
    %                 offset_idx(j-index_adjust) = [];
    %                 index_adjust = index_adjust + 1;
    %             end
    %         end

            roi_transients{end+1} = [onset_idx, offset_idx, dff_max];
            num_transients(i) = size(onset_idx,1);
        else
            roi_transients{end+1} = [];
            num_transients(i) = 0;
        end
    end
end



function [local_transients, global_transients, frac_active_time] = transient_event(dff,roi_transients,event_threshold,start_frame, stop_frame, roi_idx)
    global_transients = [];
    local_transients = [];
    [frac_active_time,event_idx] = calc_fraction_active(dff, roi_transients, event_threshold);
    transient_idx = roi_transients{roi_idx};
    onset_idx = transient_idx(:,1);
    offset_idx = transient_idx(:,2);  
    if size(onset_idx) > 0
        for j=1:size(onset_idx,1)
            if onset_idx(j) >= start_frame && offset_idx(j) <= stop_frame
                if size(intersect(onset_idx(j):offset_idx(j),find(event_idx)),1) > 1
                    global_transients = vertcat(global_transients,[onset_idx(j), offset_idx(j)]);
                else
                    local_transients = vertcat(local_transients,[onset_idx(j), offset_idx(j)]);
                end
            end
        end
    end
end

function [fraction_active, evend_idx] = calc_fraction_active(dff, transients, event_threshold)
    rois_active = zeros(size(dff));
    fraction_active = zeros(size(dff,1),1);
    evend_idx = zeros(size(dff,1),1);

    for i=1:size(dff,2)
        roi_t = transients{i};
        for j=1:size(roi_t,1)
            rois_active(roi_t(j,1):roi_t(j,2),i) = 1;
        end
    end

    for i=1:size(dff,1)
        fraction_active(i) = sum(rois_active(i,:))/size(dff,2);
    end

    evend_idx(fraction_active > event_threshold) = 1;
end

% function roi_transients = id_transients_foopsi(dff,foopsi_events,foopsi_filtered)
%     roi_transients = {};
% 
%     for i=1:size(dff,2)
%         cr_foopsi_events = foopsi_events(:,i);
%         cr_foopsi_filtered = foopsi_filtered(:,i);
%         transient_start = [];
%         transient_end = [];
%         transient_maxdf = [];
% 
%         for j=1:size(find(cr_foopsi_events))
%             event_idx = find(cr_foopsi_events);
% 
%             % determine start of transient
%             k = event_idx(j);
%             while cr_foopsi_filtered(k) > 0.01 && k > 1
%                 k = k - 1;
%             end
% 
%             % only add this transient if its not equal to the previous one
%             if size(transient_start) > 0 
%                 if k ~= transient_start(end)
%                     transient_start = [transient_start; k];
%                     % determine end of transient
%                     k = event_idx(j);
%                     while cr_foopsi_filtered(k) > 0.01 && k < size(cr_foopsi_filtered,1)
%                         k = k + 1;
%                     end
%                     transient_end = [transient_end; k];
%                     % determine max amplitude of transient
%                     transient_maxdf = [transient_maxdf; max(dff(transient_start:transient_end,i))];
%                 end
%             else
%                 transient_start = [transient_start; k];
%                 % determine end of transient
%                 k = event_idx(j);
%                 while cr_foopsi_filtered(k) > 0.01 && k < size(cr_foopsi_filtered,1)
%                     k = k + 1;
%                 end
%                 transient_end = [transient_end; k];
%                 % determine max amplitude of transient
%                 transient_maxdf = [transient_maxdf; max(dff(transient_start:transient_end,i))];
%             end
%         end
%         roi_transients{end+1} = [transient_start, transient_end, transient_maxdf];
%     end
% end


% OLD DATA PATHS
% analyze a list of files to be analyzed
%     CaMKII_RITE = ... 
%             ["/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 1/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 2/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 14/day14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 21/day21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/final dataset/CaMKII/RITE/Mouse 3/day 28/T28.sig";...
%              ];
%          
%     CaMKII_Ion_CC = ...
%             ["/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 1/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 1/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 1/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 1/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 1/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 1/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 2/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 2/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 2/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 2/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 2/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 2/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 3/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 3/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 3/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 3/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 3/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/IoN-CCI/Mouse 3/day 28/T28.sig";...
%             ];
%         
%     CaMKII_all_SHAM = ...
%             ["/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 1/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 1/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 1/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 1/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 1/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 1/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 2/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 2/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 2/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 2/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 2/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 2/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 3/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 3/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 3/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 3/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 3/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(Com-TN)/Mouse 3/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 4/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 4/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 4/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 4/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 4/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 4/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 5/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 5/day 3/T3_rigid.tif";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 5/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 5/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 5/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 5/day 28/T28.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 6/day 0/T0.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 6/day 3/T3.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 6/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 6/day 14/T14.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 6/day 21/T21.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/CaMKII/Sham/Sham(IoN-CCI)/Mouse 6/day 28/T28.sig";...
%             ];

%     Dlx_RITE_old = ...
%             ["/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 1/day 0/T8.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 1/day 3/T8.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 1/day 7/T8.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 2/day 0/T9.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 2/day 3/T9_rigid.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 2/day 7/T9.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 3/day 0/10.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 3/day 3/T10.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 3/day 7/T10.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 4/day 0/T11.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 4/day 3/T11.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 4/day 7/T11.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 5/day 0/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 5/day 3/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 5/day 7/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 6/day 0/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 6/day 3/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 6/day 7/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 7/day 0/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 7/day 3/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 7/day 7/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 8/day 0/T_rigid.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 8/day 3/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 8/day 7/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 9/day 0/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 9/day 3/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 9/day 7/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 10/day 0/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 10/day 3/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/RITE/Mouse 10/day 7/T.sig";
%              ];
% 
%     Dlx_Sham = [...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 1/day 0/T4.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 1/day 3/T4_rigid.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 1/day 7/T4.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 2/day 0/T5.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 2/day 3/T5.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 2/day 7/T5.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 3/day 0/T6.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 3/day 3/T6.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 3/day 7/T6.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 4/day 0/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 4/day 3/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 4/day 7/T7.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 5/day 0/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 5/day 3/T.sig";...  
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 5/day 7/T_rigid.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 6/day 0/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 6/day 3/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 6/day 7/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 7/day 0/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 7/day 3/T.sig";...
%              "/Users/lukasfischer/Work/exps/Shiqian/Dlx data/Sham/Mouse 7/day 7/T.sig";
%              ];
    