function frame = sbxRead(Info, index)

    %SBXREAD Read individual frames from .sbx file.
    %   frame = SBXREAD(Info, index) gives the frame at the indicated index.
    %
    %   Info: structure
    %       Structure generated by sbxInfo from corresponding .mat file.
    %
    %   index: integer
    %       Index of the frame to be read. The first index is 0.
    %
    %   frame: uint16
    %       Array with dimensions (Info.sz(1), Info.sz(2)).
    
    fileID = fopen([Info.Directory.folder, Info.Directory.name, '.sbx'], 'r');
    
    % set access point to start of indicated frame in bytes
    fseek(fileID, index*Info.bytesPerFrame, 'bof');
    
    % read frame in terms of samples
    frame = fread(fileID, Info.samplesPerFrame, 'uint16=>uint16');
    
    if ~isempty(frame)
        frame = reshape(frame, [Info.nChannels, Info.sz(2), Info.sz(1)]);
    else
        waitfor(msgbox('Error: Empty frame. Index range likely outside of bounds.'));
        error('Empty frame. Index range likely outside of bounds.');
    end
        
    frame = squeeze(intmax('uint16') - permute(frame, [1, 3, 2]));

    fclose(fileID);
    
end